site_name: EventFlow
site_url: https://geteventflow.net/
theme: material
docs_dir: Documentation

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true

