name: pull-requests

on:
  push:
    branches: [ develop-v0 ]
  pull_request:
    branches: [ develop-v0 ]

jobs:
  build:
    runs-on: windows-latest
    env:
      HELPZ_POSTGRESQL_PASS: postgres
      EVENTFLOW_MSSQL_SERVER: 127.0.0.1,1433
      EVENTFLOW_MSSQL_USER: sa
      EVENTFLOW_MSSQL_PASS: Password12!

    steps:
    - uses: actions/checkout@v4

    - run: |
        powershell -NoProfile -ExecutionPolicy unrestricted -Command ".\up_integration-test-env.ps1"

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          3.0.x
          3.1.x
          6.0.x

    - name: Install Bake 
      run: dotnet tool install -g --version 0.27.40-beta Bake

    - name: Run Bake
      run: |
        bake run --build-version 0.${{ github.run_number }}.${{ github.run_attempt }}
    - name: Upload NuGet packages
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: packages
        path: "**/*nupkg"
        if-no-files-found: error

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: test-results
        path: "**/*.trx"
        if-no-files-found: error
